"""Safe deterministic packaging for the single-file in-platform strategy editor."""

from __future__ import annotations

import hashlib
import io
import json
import zipfile
from dataclasses import dataclass
from typing import Literal, TypedDict

from orbit_api.builtin_strategies.registry import BASIC
from orbit_api.domain.strategy_versions import StrategyPackageInvalidError

MAX_SOURCE_BYTES = 128 * 1024
_ZIP_TIME = (2026, 1, 1, 0, 0, 0)


class GuidedParameters(TypedDict):
    launchRatio: float
    minimumShips: int
    targetPreference: Literal["nearest", "weakest"]


DEFAULT_PARAMETERS: GuidedParameters = {
    "launchRatio": 0.35,
    "minimumShips": 4,
    "targetPreference": "nearest",
}


@dataclass(frozen=True)
class SourcePackage:
    content: bytes
    content_hash: str
    manifest: dict[str, object]


def platform_basic_source() -> str:
    source_path, _target = BASIC.source_files[0]
    return source_path.read_text(encoding="utf-8")


def validate_source(source: str) -> bytes:
    if not isinstance(source, str):
        raise StrategyPackageInvalidError("source must be text", field="sourceCode")
    try:
        encoded = source.encode("utf-8")
    except UnicodeEncodeError as error:
        raise StrategyPackageInvalidError("source must be UTF-8", field="sourceCode") from error
    if not encoded or len(encoded) > MAX_SOURCE_BYTES:
        raise StrategyPackageInvalidError(
            f"source must contain 1-{MAX_SOURCE_BYTES} UTF-8 bytes",
            field="sourceCode",
        )
    if "\x00" in source:
        raise StrategyPackageInvalidError("source cannot contain NUL bytes", field="sourceCode")
    return encoded


def build_source_package(source: str) -> SourcePackage:
    encoded = validate_source(source)
    manifest: dict[str, object] = {
        "schemaVersion": 1,
        "entrypoint": "main.py:agent",
        "editor": "orbit-strategy-lab-v1",
    }
    files = {
        "main.py": encoded,
        "manifest.json": json.dumps(manifest, separators=(",", ":")).encode(),
    }
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, content in sorted(files.items()):
            info = zipfile.ZipInfo(name, date_time=_ZIP_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100444 << 16
            archive.writestr(info, content)
    package = output.getvalue()
    return SourcePackage(package, hashlib.sha256(package).hexdigest(), manifest)


def guided_source(
    launch_ratio: float,
    minimum_ships: int,
    target_preference: Literal["nearest", "weakest"] = "nearest",
) -> str:
    ratio = min(0.9, max(0.1, float(launch_ratio)))
    minimum = min(100, max(1, int(minimum_ships)))
    target_key = (
        'float(planet.get("ships", 0))'
        if target_preference == "weakest"
        else '((float(planet["x"]) - float(source["x"])) ** 2 '
        '+ (float(planet["y"]) - float(source["y"])) ** 2)'
    )
    return f'''"""Generated by Orbit/Wars Strategy Lab. Switch to Code mode for custom logic."""

import math
from typing import Any

LAUNCH_RATIO = {ratio:.2f}
MINIMUM_SHIPS = {minimum}
TARGET_PREFERENCE = "{target_preference}"


def agent(obs: dict[str, Any]) -> list[list[int | float]]:
    player = int(obs.get("player", 0))
    planets = obs.get("planets", [])
    owned = [planet for planet in planets if int(planet.get("owner", -1)) == player]
    targets = [planet for planet in planets if int(planet.get("owner", -1)) != player]
    if not owned or not targets:
        return []
    source = max(owned, key=lambda planet: float(planet.get("ships", 0)))
    ships = int(float(source.get("ships", 0)) * LAUNCH_RATIO)
    if ships < MINIMUM_SHIPS:
        return []
    target = min(targets, key=lambda planet: {target_key})
    angle = math.atan2(
        float(target["y"]) - float(source["y"]),
        float(target["x"]) - float(source["x"]),
    ) % math.tau
    return [[int(source["id"]), angle, ships]]
'''
